default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DB_PORT') { 5432 } %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV.fetch('DB_USERNAME') { 'postgres' } %>
  password: <%= ENV['DB_PASSWORD'] %>
development:
  <<: *default
test:
  <<: *default
  database: myapp_us_test
production:
  <<: *default
  <<: *default
  database: myapp_us_production
  username: myapp_us
  password: <%= ENV['MYAPP_US_DATABASE_PASSWORD'] %>





